export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightcoral"}}>Header</header>

          {children}
        <footer style={{backgroundColor:"lightskyblue"}}>Footer</footer>

      </body>
    </html>
  )
}
